[build]
  command = "npm ci && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[build.processing]
  skip_processing = true


[build.environment]
  NETLIFY_BUILD_DEBUG = "true"
